version: "3"
services:
  mongodb:
    image: mongo:6.0.5
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: --smallfiles
  app:
    image: testspring # 우리가 Dockerfile에서 지정했던 app 이름
    ports:
      - 8080:8080
    links:
      - mongodb