name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout release
        uses: actions/checkout@v2

      - name: Archive drcloud
        run: tar cvfz drcloud.tar.gz .

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp drcloud.tar.gz s3://github-action-codedeploy-s3/archive/

      - name: Deploy with AWS CodeDeploy
        run: aws deploy create-deployment \
          --application-name githubaction-test \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name githubaction-test-group \
          --s3-location bucket=github-action-codedeploy-s3,bundleType=tgz,key=archive/drcloud.tar.gz
